In [62]:
import pandas as pd

df = pd.read_csv('df.csv', parse_dates=['FECHA'])
predicciones = pd.read_csv('Predicciones.csv', parse_dates=['FECHA'])

In [63]:
df['TIPO_REGISTRO'] = 'Venta Real'
df['MODELO'] = 'Venta Real'
predicciones['TIPO_REGISTRO'] = 'Prediccion'

In [64]:
df

,FECHA,NOMBRE_ALMACEN,SKU,CANTIDAD,TIPO_REGISTRO,MODELO
0,2022-01-03,4 CAMINOS,T23C2139CH,0.0,Venta Real,Venta Real
1,2022-01-10,4 CAMINOS,T23C2139CH,0.0,Venta Real,Venta Real
2,2022-01-17,4 CAMINOS,T23C2139CH,0.0,Venta Real,Venta Real
3,2022-01-24,4 CAMINOS,T23C2139CH,0.0,Venta Real,Venta Real
4,2022-01-31,4 CAMINOS,T23C2139CH,0.0,Venta Real,Venta Real
...,...,...,...,...,...,...
81244,2024-05-27,XOCHIMILCO,TBAD3008GD,0.0,Venta Real,Venta Real
81245,2024-06-03,XOCHIMILCO,TBAD3008GD,0.0,Venta Real,Venta Real
81246,2024-06-10,XOCHIMILCO,TBAD3008GD,0.0,Venta Real,Venta Real
81247,2024-06-17,XOCHIMILCO,TBAD3008GD,0.0,Venta Real,Venta Real
81248,2024-06-24,XOCHIMILCO,TBAD3008GD,0.0,Venta Real,Venta Real

In [65]:
df_todo = pd.concat([df, predicciones], axis=0)

In [66]:
predicciones.drop(['PARAMETROS', 'LAGS'], axis=1)

predicciones = predicciones[['FECHA', 'NOMBRE_ALMACEN', 'SKU', 'CANTIDAD', 'TIPO_REGISTRO', 'MODELO']]
predicciones

,FECHA,NOMBRE_ALMACEN,SKU,CANTIDAD,TIPO_REGISTRO,MODELO
0,2024-06-10,4 CAMINOS,T23C2139CH,0.0,Prediccion,RandomForest
1,2024-06-17,4 CAMINOS,T23C2139CH,0.0,Prediccion,RandomForest
2,2024-06-24,4 CAMINOS,T23C2139CH,0.0,Prediccion,RandomForest
3,2024-06-10,4 CAMINOS,T23C2139CH,0.0,Prediccion,Prophet
4,2024-06-17,4 CAMINOS,T23C2139CH,0.0,Prediccion,Prophet
...,...,...,...,...,...,...
13495,2024-06-17,XOCHIMILCO,TBAD3008GD,1.0,Prediccion,Poisson
13496,2024-06-24,XOCHIMILCO,TBAD3008GD,1.0,Prediccion,Poisson
13497,2024-06-10,XOCHIMILCO,TBAD3008GD,0.0,Prediccion,AditivoBaseline
13498,2024-06-17,XOCHIMILCO,TBAD3008GD,0.0,Prediccion,AditivoBaseline
13499,2024-06-24,XOCHIMILCO,TBAD3008GD,0.0,Prediccion,AditivoBaseline

In [67]:
todo = pd.concat([df, predicciones], axis=0)
todo = todo.sort_values(['NOMBRE_ALMACEN', 'SKU', 'FECHA', 'TIPO_REGISTRO', 'MODELO'])
todo.dtypes

FECHA             datetime64[ns]
NOMBRE_ALMACEN            object
SKU                       object
CANTIDAD                 float64
TIPO_REGISTRO             object
MODELO                    object
dtype: object

In [69]:
todo.to_csv('Real y Predicciones.csv')